apiVersion: v1
entries:
  account-server:
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2024-09-17T08:45:38.635630389Z"
    description: 'A helm chart for the account-server that provides NATS accounting. '
    digest: 6a812d6db6cc1334f1cc797f74e7fe47f73e5c88bc27ae116fba4ed0d0fdaa4c
    home: https://github.com/zeiss/natz-operator
    keywords:
    - nats
    - accounting
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Sebastian Doell
      url: https://github.com/katallaxie
    name: account-server
    sources:
    - https://github.com/zeiss/natz-operator/tree/main/helm/charts/account-server
    - https://github.com/zeiss/natz-operator
    urls:
    - https://github.com/ZEISS/natz-operator/releases/download/account-server-0.0.4/account-server-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2024-09-17T07:04:18.077180933Z"
    description: 'A helm chart for the account-server that provides NATS accounting. '
    digest: 92c5e93e057366b9004ecc6a064b37c181f43a79a0bcebe37eb6e743598402f3
    home: https://github.com/zeiss/natz-operator
    keywords:
    - nats
    - accounting
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Sebastian Doell
      url: https://github.com/katallaxie
    name: account-server
    sources:
    - https://github.com/zeiss/natz-operator/tree/main/helm/charts/account-server
    - https://github.com/zeiss/natz-operator
    urls:
    - https://github.com/ZEISS/natz-operator/releases/download/account-server-0.0.3/account-server-0.0.3.tgz
    version: 0.0.3
  natz-operator:
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2024-09-17T08:45:38.814807372Z"
    description: 'A helm chart for the natz-operator that provides NATS accounting. '
    digest: 4f28c05b780f2d4063a60b324c24d84600e081e4f19f930cb82d7c486363cd85
    home: https://github.com/zeiss/natz-operator
    keywords:
    - nats
    - accounting
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Sebastian Doell
      url: https://github.com/katallaxie
    name: natz-operator
    sources:
    - https://github.com/zeiss/natz-operator/tree/main/helm/charts/natz-operator
    - https://github.com/zeiss/natz-operator
    urls:
    - https://github.com/ZEISS/natz-operator/releases/download/natz-operator-0.0.4/natz-operator-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2024-09-17T07:04:18.181593792Z"
    description: 'A helm chart for the natz-operator that provides NATS accounting. '
    digest: 8b1a3ea6804f314e197db71ac38a0de708e614ea7c745998601a11a28a41d880
    home: https://github.com/zeiss/natz-operator
    keywords:
    - nats
    - accounting
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Sebastian Doell
      url: https://github.com/katallaxie
    name: natz-operator
    sources:
    - https://github.com/zeiss/natz-operator/tree/main/helm/charts/natz-operator
    - https://github.com/zeiss/natz-operator
    urls:
    - https://github.com/ZEISS/natz-operator/releases/download/natz-operator-0.0.3/natz-operator-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2024-09-16T10:57:49.090890139Z"
    description: 'A helm chart for the natz-operator that provides NATS accounting. '
    digest: 6b9e817aeace269dd575c82bd0b4fabac5adc7ea1a233b7e877865500cfe264e
    home: https://github.com/zeiss/natz-operator
    keywords:
    - nats
    - accounting
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Sebastian Doell
      url: https://github.com/katallaxie
    name: natz-operator
    sources:
    - https://github.com/zeiss/natz-operator/tree/main/helm/charts/natz-operator
    - https://github.com/zeiss/natz-operator
    urls:
    - https://github.com/ZEISS/natz-operator/releases/download/natz-operator-0.0.2/natz-operator-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1-beta.3
    created: "2024-09-16T10:13:26.725466164Z"
    description: 'A helm chart for the natz-operator that provides NATS accounting. '
    digest: ddb8845d3c0b118ba0dee2579b3dd807e92d923670fca1aeb64597a5e32ca492
    home: https://github.com/zeiss/natz-operator
    keywords:
    - nats
    - accounting
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Sebastian Doell
      url: https://github.com/katallaxie
    name: natz-operator
    sources:
    - https://github.com/zeiss/natz-operator/tree/main/helm/charts/natz-operator
    - https://github.com/zeiss/natz-operator
    urls:
    - https://github.com/ZEISS/natz-operator/releases/download/natz-operator-0.0.1-beta.3/natz-operator-0.0.1-beta.3.tgz
    version: 0.0.1-beta.3
  - apiVersion: v2
    appVersion: 0.0.1-beta.2
    created: "2024-09-16T09:30:15.911223725Z"
    description: 'A helm chart for the natz-operator that provides NATS accounting. '
    digest: 3996407e9f83d1b849e0c7409d6d5c657cf23cf5192787cc3862cb2a94bbd8a6
    home: https://github.com/zeiss/natz-operator
    keywords:
    - nats
    - accounting
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Sebastian Doell
      url: https://github.com/katallaxie
    name: natz-operator
    sources:
    - https://github.com/zeiss/natz-operator/tree/main/helm/charts/natz-operator
    - https://github.com/zeiss/natz-operator
    urls:
    - https://github.com/ZEISS/natz-operator/releases/download/natz-operator-0.0.1-beta.2/natz-operator-0.0.1-beta.2.tgz
    version: 0.0.1-beta.2
generated: "2024-09-17T08:45:38.81482752Z"
