apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-server.fullname" . }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "account-server.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "account-server.fullname" . }}
    spec:
      serviceAccountName: {{ include "account-server.serviceAccountName" . }}
      containers:
      - name: account-server
        image: {{ default .Values.global.image.repository .Values.controller.image.repository }}:{{ default (include "natz-operator.defaultTag" .) .Values.controller.image.tag }}
        args: ["--metrics-bind-address", ":12003", "--health-probe-bind-address", ":12002"]
        env:
        - name: "NATS_URL"
          value: "nats://${NATS_RELEASE_NAME}-nats-headless.nats-cluster.svc.cluster.local"
        - name: "NATS_CREDS_FILE"
          value: "/etc/nats/user.creds"
        - name: "POD_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        volumeMounts:
        - name: "credentials"
          mountPath: "/etc/nats"
          readOnly: true
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: "credentials"
        secret:
          defaultMode: 420
          secretName: "root-operator-jwt"
          items:
          - key: "user.creds"
            path: "user.creds"
            mode: 420