apiVersion: natz.zeiss.com/v1alpha1
kind: NatsConfig
metadata:
  name: nats-default-config
spec:
  operatorRef:
    name: natsoperator-sample
  systemAccountRef:
    name: natsoperator-system
  gateways:
    - name: harry
      namespace: default
  config:
    http_port: 8223