apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nats
  namespace: knative-eventing
data:
  eventing-nats: |
    url: nats://nats.knative-eventing.svc.cluster.local
    auth:
      credentialFile:
        secret:
          name: knative-eventing-user
          key: user.creds
    connOpts:
      retryOnFailedConnect: true
      maxReconnects: 5
      reconnectWaitMilliseconds: 2000
      reconnectJitterMilliseconds: 100
      reconnectJitterTLSMilliseconds: 1000