apiVersion: v1
kind: ConfigMap
metadata:
  name: config-natjsm-channel
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: devel
data:
  channelTemplateSpec: |
    apiVersion: messaging.knative.dev/v1alpha1
    kind: NatsJetStreamChannel