apiVersion: v1
kind: Secret
metadata:
  name: gateway-north-secret
data:
  key: NjJlYjE2NWMwNzBhNDFkNWMxYjU4ZDlkM2Q3MjVjYTE=
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsGateway
metadata:
  name: harry
spec:
  url: nats://nats.north:4222
  username: harry
  password:
    secretKeyRef:
      key: key
      name: gateway-north-secret
