apiVersion: natz.zeiss.com/v1alpha1
kind: NatsSigningKey
metadata:
  name: natsoperator-sample
spec:
  type: Operator
  prevent_deletion: true
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsOperator
metadata:
  name: natsoperator-sample
spec:
  signing_keys:
    - name: natsoperator-sample
