apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: natsoperator-system-private-key
spec:
  type: Account
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsKey
metadata:
  name: natsoperator-system-signing-key
spec:
  type: Account
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsAccount
metadata:
  name: natsoperator-system
spec:
  name: SYS
  signerKeyRef:
    name: natsoperator-system-private-key
  privateKey:
    name: natsoperator-system-private-key
  signingKeys:
    - name: natsoperator-system-signing-key
  pub:
    allow:
      - $SYS.REQ.ACCOUNT.*.CLAIMS.LOOKUP
      - $SYS.REQ.CLAIMS.UPDATE
    sub:
      allow:
        - $SYS.REQ.ACCOUNT.*.CLAIMS.LOOKUP
    resp:
      max: -1
      ttl: -1
export:
  limits:
    exports: -1
    imports: -1
    subs: -1
    payload: -1
    data: -1
    conn: -1
    wildcards: true
    disallow_bearer: true
