apiVersion: natz.zeiss.com/v1alpha1
kind: NatsPrivateKey
metadata:
  name: natsuser-system-private-key
spec:
  type: User
---
apiVersion: natz.zeiss.com/v1alpha1
kind: NatsUser
metadata:
  name: natsuser-system
spec:
  privateKey:
    name: natsuser-system-private-key
  accountSigningKey:
    name: natsoperator-system-signing-key
  limits:
    payload: -1
    subs: -1
    data: -1
