apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "natz-operator.fullname" . }}-manager-role
  labels:
  {{- include "natz-operator.labels" . | nindent 4 }}
rules:
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsoperators/finalizers
  verbs:
  - update
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsusers/finalizers
  verbs:
  - update
- apiGroups:
  - natz.zeiss.com
  resources:
  - natsusers/status
  verbs:
  - get
  - patch
  - update
